### ISSUE TITLE
Failure to create a symbols feed in `Publish CTI Validated Assets` stage

### ISSUE THREAD

**Issue by MilenaHristova** [dotnet/arcade-services#2412]
A failure to create AzureDevOps symbols feed
The error comes from Arcade SDK - the `PublishArtifactsInManifest` task

**Build**  https://dev.azure.com/dnceng/internal/_build/results?buildId=2124768&view=logs&j=8667c75e-c9c8-5a72-3326-7d35d151733c&t=648bbdf3-1356-5b63-95ae-560e1b5f90bf&s=c7c66624-49ea-58ba-1f00-c2864485acd9

**Error**
```
Feed 'darc-pub-sym-dotnet-templating-67c5daf1' was not created. Request failed with status code ServiceUnavailable.
```

```
##[error].packages\microsoft.dotnet.arcade.sdk\8.0.0-beta.23055.2\tools\SdkTasks\PublishArtifactsInManifest.proj(144,5): error : Problems creating an AzureDevOps (symbols) feed for repository 'dotnet-templating' and commit '67c5daf1d41d1e4a970b414ca304e6f0851e8666'.
   at Microsoft.DotNet.Build.Tasks.Feed.SetupTargetFeedConfigV3.CreateStableSymbolsFeedIfNeeded() in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/model/SetupTargetFeedConfigV3.cs:line 208
   at Microsoft.DotNet.Build.Tasks.Feed.SetupTargetFeedConfigV3.Feeds()+MoveNext() in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/model/SetupTargetFeedConfigV3.cs:line 98
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.DistinctIterator`1.ToList()
   at Microsoft.DotNet.Build.Tasks.Feed.SetupTargetFeedConfigV3.Setup() in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/model/SetupTargetFeedConfigV3.cs:line 86
   at Microsoft.DotNet.Build.Tasks.Feed.PublishArtifactsInManifestV3.ExecuteAsync() in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestV3.cs:line 151
```

**Goal**
Investigate cause of the issue - a temporary service unavailability or a bug in the feed creation logic. If it's  we can add a retry mechanism for that step

**Comment by MilenaHristova** [comment]
This is a temporary AzureDevOps service unavailability. The job already has a retry mechanism and had 2 attempts, but in this case retrying multiple times won't solve the issue. Nothing to fix here
