### ISSUE TITLE
[Darc] creating a duplicate default channel results in an Internal server error

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade-services#2804]
Using darc to attempt to create a default channel that already exists results in an error:

```
fail: Error: Failed to add a new default channel association.
      Microsoft.DotNet.Maestro.Client.RestApiException`1[Microsoft.DotNet.Maestro.Client.Models.ApiError]: The response contained an invalid status code 500 Internal Server Error

Body: {"message":"An error occured.","errors":null}
         at Microsoft.DotNet.Maestro.Client.DefaultChannels.OnCreateFailed(Request req, Response res) in /_/src/Maestro/Client/src/Generated/DefaultChannels.cs:line 222
         at Microsoft.DotNet.Maestro.Client.DefaultChannels.CreateAsync(DefaultChannelCreateData body, CancellationToken cancellationToken) in /_/src/Maestro/Client/src/Generated/DefaultChannels.cs:line 193
         at Microsoft.DotNet.DarcLib.MaestroApiBarClient.AddDefaultChannelAsync(String repository, String branch, String channel) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/MaestroApiBarClient.cs:line 89
         at Microsoft.DotNet.Darc.Operations.AddDefaultChannelOperation.ExecuteAsync() in /_/src/Microsoft.DotNet.Darc/src/Darc/Operations/AddDefaultChannelOperation.cs:line 40
```

This is easy to repro by running the same create-default-channel command twice in a row.

We should:
* Not 500 here
* return a useful message that the default channel with the provided inputs already exists.

**Comment by dkurepa** [comment]
I was unable to recreate this error with the `darc add-default-channel --repo https://github.com/dotnet/arcade-services --branch main --channel ".NET Eng Services - Int"` command, even after running it multiple times in a row

**Comment by riarenas** [comment]
Might not be every duplicate, but something special in this one? Tested with the latest darc

```
darc --version
Microsoft.DotNet 1.1.0-beta.23415.1+7ca59947f4f342e61a11c8c949d9a7a7eba2f6d4
 darc add-default-channel --channel "General Testing Internal" --branch "exp/blog-redactor" --repo https://devdiv.visualstudio.com/DevDiv/_git/DotNet-msbuild-Trusted
fail: Error: Failed to add a new default channel association.
      Microsoft.DotNet.Maestro.Client.RestApiException`1[Microsoft.DotNet.Maestro.Client.Models.ApiError]: The response contained an invalid status code 500 Internal Server Error

Body: {"message":"An error occured.","errors":null}
         at Microsoft.DotNet.Maestro.Client.DefaultChannels.OnCreateFailed(Request req, Response res) in /_/src/Maestro/Client/src/Generated/DefaultChannels.cs:line 225
         at Microsoft.DotNet.Maestro.Client.DefaultChannels.CreateAsync(DefaultChannelCreateData body, CancellationToken cancellationToken) in /_/src/Maestro/Client/src/Generated/DefaultChannels.cs:line 196
         at Microsoft.DotNet.DarcLib.MaestroApiBarClient.AddDefaultChannelAsync(String repository, String branch, String channel) in /_/src/Microsoft.DotNet.Darc/DarcLib/MaestroApiBarClient.cs:line 88
         at Microsoft.DotNet.Darc.Operations.AddDefaultChannelOperation.ExecuteAsync() in /_/src/Microsoft.DotNet.Darc/Darc/Operations/AddDefaultChannelOperation.cs:line 39
```

**Comment by dkurepa** [comment]
Yup, that one did the trick. I'll look into it, thanks

**Comment by dkurepa** [comment]
What's very weird here is that the Repository name in the logs, is different from the one we're sending in the Darc request.
When running darc with `https://devdiv.visualstudio.com/DevDiv/_git/DotNet-msbuild-Trusted` repository as the repo argument, it somehow transforms into `https://dev.azure.com/devdiv/DevDiv/_git/DotNet-msbuild-Trusted` when it reaches the Maestro API

**Comment by dkurepa** [comment]
I think this is a very weird edge base. When running `darc add-default-channel --channel "General Testing Internal" --branch "exp/blog-redactor" --repo https://devdiv.visualstudio.com/DevDiv/_git/DotNet-msbuild-Trusted`, Maestro checks if this DefaultChannel already exists in the BAR. It doesn't find it so it tries to add it, however somehow, while it's being added, the original url `https://devdiv.visualstudio.com/DevDiv/_git/DotNet-msbuild-Trusted` gets redirected to `https://dev.azure.com/devdiv/DevDiv/_git/DotNet-msbuild-Trusted`, which Maestro tries to add to BAR. The DefaultChannel for this repo, branch, channel combination already exists, so it throws an exception.
So this looks to be an edge case that happens because of URL redirection

**Comment by dkurepa** [comment]
closing this issue since it's a very rare edge case explained above
