### ISSUE TITLE
Maestro++ is not opening dependency update PRs for AzDo repos.

### ISSUE THREAD

**Issue by andriipatsula** [dotnet/arcade-services#3382]
FR request: [link](https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1709710028461?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1709710028461&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1709710028461)

* The repo is https://dev.azure.com/devdiv/DevDiv/_git/vs-code-coverage and it misses dependency updates from arcade for about 1 month.
* On the other hand, it does receive dependency updates from other repos: `microsoft/testanywhere`, `microsoft/testfx`
https://dev.azure.com/devdiv/DevDiv/_git/vs-code-coverage/pullrequests?_a=completed
* GH repos like runtime are receiving arcade dependency updates quite frequently:
https://github.com/dotnet/runtime/pulls?q=is%3Apr+%22dotnet%2Farcade%22
* Customers are able to manually trigger dependency updates via `darc update-dependencies`
* Seems the issue start happening ~ 7th of Feb after the https://github.com/dotnet/arcade-services/pull/3272, but I am not sure if that's related.

```sql
-- Returns 158 TargetRepository (25 - AzDo repos, 6 in DevDiv and 19 in dnceng)
SELECT distinct TargetRepository FROM [dbo].[DependencyFlowEvents] (nolock)
where SourceRepository like '%arcade'
```
One more example: the last time maestro++ triggered the `arcade -> dotnet-wpf-int` (which is under dnceng) subscription was on 6th of Feb
 https://dev.azure.com/dnceng/internal/_git/dotnet-wpf-int/pullrequest/32149

```sql
-- Id: 3BE50526-8796-43B2-B8EE-08DC3861575E
select * from dbo.Subscriptions (nolock)
where TargetRepository like '%vs-code-coverage' and SourceRepository like '%arcade'
```

**Comment by andriipatsula** [comment]
```kusto
traces
| where timestamp between (make_datetime(2024, 02, 20) .. make_datetime(2024, 02, 21))
| where operation_Id == "a5279c0240c7495b51f970325317ef8d"
```

> 2/20/2024, 1:41:42.068 PM Updating subscriptions for merged PR
2/20/2024, 1:41:42.102 PM Try to clean up the PR branch https://dev.azure.com/devdiv/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_apis/git/repositories/56684359-da38-4464-a440-399c4572d5aa/pullRequests/530031
2/20/2024, 1:41:42.880 PM A '404 - NotFound' status was returned for a HTTP request. We'll set the retries amount to 0. Error details: {"$id":"1","innerException":null,"message":"TF401175:The version descriptor <Branch: darc-main-eba4063e-53d0-4633-a745-236aed79fff7 > could not be r
2/20/2024, 1:41:42.880 PM There was an error executing method 'GET' against URI '_apis/git/repositories/56684359-da38-4464-a440-399c4572d5aa/commits?branch=darc-main-eba4063e-53d0-4633-a745-236aed79fff7' after 15 attempts. Exception: System.Net.Http.HttpRequestException:

**Comment by premun** [comment]
I tried to trigger one of the problematic subscriptions and received this:

```
Actor's async method threw an exception. Method name: IPullRequestActor.UpdateAssetsAsync, actor type: PullRequestActor, actor ID: be0f19d8-de21-40b7-9420-08dc11e2fbb8, exception: System.ArgumentException: Repository URI should be in the form https://dev.azure.com/:account/:project/_git/:repo or https://:account.visualstudio.com/:project/_git/:repo
at Microsoft.DotNet.DarcLib.AzureDevOpsClient.ParseRepoUri(String repoUri) in /_/src/Microsoft.DotNet.Darc/DarcLib/AzureDevOpsClient.cs:line 943
at Microsoft.DotNet.DarcLib.AzureDevOpsClient.GetFileContentsAsync(String filePath, String repoUri, String branch) in /_/src/Microsoft.DotNet.Darc/DarcLib/AzureDevOpsClient.cs:line 87
at Microsoft.DotNet.DarcLib.DependencyFileManager.ReadGlobalJsonAsync(String repoUri, String branch) in /_/src/Microsoft.DotNet.Darc/DarcLib/Helpers/DependencyFileManager.cs:line 106
at Microsoft.DotNet.DarcLib.DependencyFileManager.ReadToolsDotnetVersionAsync(String repoUri, String commit) in /_/src/Microsoft.DotNet.Darc/DarcLib/Helpers/DependencyFileManager.cs:line 144
at Microsoft.DotNet.DarcLib.Remote.CommitUpdatesAsync(String repoUri, String branch, IRemoteFactory remoteFactory, IBasicBarClient barClient, List`1 itemsToUpdate, String message) in /_/src/Microsoft.DotNet.Darc/DarcLib/Actions/Remote.cs:line 193
at SubscriptionActorService.PullRequestBuilder.CalculatePRDescriptionAndCommitUpdatesAsync(List`1 requiredUpdates, String currentDescription, String targetRepository, String newBranchName) in /_/src/Maestro/SubscriptionActorService/PullRequestBuilder.cs:line 175
at SubscriptionActorService.PullRequestActorImplementation.CreatePullRequestAsync(List`1 updates) in /_/src/Maestro/SubscriptionActorService/PullRequestActor.cs:line 773
at SubscriptionActorService.PullRequestActorImplementation.CreatePullRequestAsync(List`1 updates) in /_/src/Maestro/SubscriptionActorService/PullRequestActor.cs:line 773
at SubscriptionActorService.PullRequestActorImplementation.UpdateAssetsAsync(Guid subscriptionId, Int32 buildId, String sourceRepo, String sourceSha, List`1 assets) in /_/src/Maestro/SubscriptionActorService/PullRequestActor.cs:line 671
at Microsoft.DotNet.ServiceFabric.ServiceHost.AsyncInterceptor.<>c__DisplayClass8_0.<<InterceptAsync>b__0>d.MoveNext()

**Comment by premun** [comment]
From the exception it's clear that we are trying to use an Azure DevOps git remote class against a public Arcade GitHub repo when checking the Arcade-related version files (global.json etc). It fails because it can't read the remote files this way. We now create the correct remote client and use it.

**Comment by premun** [comment]
So it seems we have an E2E test for Arcade updates: https://github.com/dotnet/arcade-services/blob/db2a93228843bc7c36c02c0eead467bc3ec192dd/test/Maestro.ScenarioTests/ScenarioTests_SdkUpdate.cs#L31

But it targets GitHub repos. We should copy the test and target an AzDO repo too to get coverage for this.

**Comment by premun** [comment]
I tested a previously broken subscription and a PR got opened correctly.

**Comment by premun** [comment]
Okay, this is done now
