### ISSUE TITLE
Register ITelemetryRecorder service

### ISSUE THREAD

**Issue by MilenaHristova** [dotnet/arcade-services#3507]
Fix a issue in darc introduced by https://github.com/dotnet/arcade-services/pull/3492 that's causing failures in arcade-validation

Error message
```
      System.InvalidOperationException: Unable to resolve service for type 'Microsoft.DotNet.DarcLib.ITelemetryRecorder' while attempting to activate 'Microsoft.DotNet.DarcLib.GitRepoFactory'.
         at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
         at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
         at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance[T](IServiceProvider provider, Object[] parameters)
```

**Comment by MilenaHristova** [comment]
PR: https://github.com/dotnet/arcade-services/pull/3505

**Comment by premun** [comment]
I verified the fix works
